[package]
name = "markedly-ggez"
version = "0.1.0"
authors = ["Layl <LaylConway@users.noreply.github.com>"]

[dependencies]
ggez = "0.4"
nalgebra = "0.14"
markedly = { path = "../markedly" }
metrohash = "1"
